removed _init_function and updated _init_cmd - signed-off-by: trimstray <contact@nslab.at>

diff --git a/src/helpers b/src/helpers
--- a/src/helpers
+++ b/src/helpers
@@ -349,130 +349,112 @@ function _sprintf() {
 
 function _init_cmd() {
 
+  # shellcheck disable=SC2034
   local _FUNCTION_ID="_init_cmd"
-  local _STATE="0"
+  local _STATE=0
 
-  local _cmd="$1"
+  local _cmd=("$@")
+  local _full_command=()
 
-  # Uncomment if you want to display executed commands.
-  # _sprintf "info" "init: \"$_cmd\""
-
-  _logger "info" \
-    "${_FUNCTION_ID}()" \
-    "init: $_cmd"
-
-  # Execute command and exit save to file.
   # shellcheck disable=SC2154
-  "$_cmd" >>"$_log_stdout" 2>&1 &
+  if [[ "$tor" == "true" ]] ; then
 
-  # We keep pid of the last command.
-  _pid="$!"
-
-  # When the '(command) &' command is performed.
-  _sprintf "spin" "$_pid"
-
-  # Very important line:
-  # We define the state of the output job from the background.
-  wait "$_pid" &>/dev/null && _state="0" || _state="1"
-
-  if [[ "$_state" -eq 0 ]] ; then
-
-    _logger "info" \
-      "${_FUNCTION_ID}()" \
-      "result: pass"
-
-  else
-
-    _sprintf "stop" "result: fail"
-
-    _logger "stop" \
-      "${_FUNCTION_ID}()" \
-      "result: fail"
+    _full_command+=("proxychains")
 
   fi
 
-  _STATE="$_state"
+  # shellcheck disable=SC2154
+  if [[ "$terminal" == "external" ]] ; then
 
-  return "$_STATE"
+    printf "\n\e[1;39m%s\e[m:\n" "terminal"
+    printf "\e[1;39m%c\e[m \e[0;30m%s\e[m\n" ">" "$terminal"
+    _full_command+=("${_xterm}")
 
-}
+  else
 
-# ``````````````````````````````````````````````````````````````````````````````
-# Function name: _init_function()
-#
-# Description:
-#   It deals with launching functions:
-#     - creates a simple environment for the functions you perform
-#     - operates on message to display and command to execute
-#
-# Usage:
-#   _init_function function_name params
-#
-# Examples:
-#   _init_function "CheckConn 172.20.20.50 22"
-#
+    printf "\n\e[1;39m%s\e[m:\n" "terminal"
+    printf "\e[1;39m%c\e[m \e[0;30m%s\e[m\n" ">" "internal"
 
-function _init_function() {
+  fi
 
-  local _FUNCTION_ID="_init_function"
-  local _STATE="0"
+  _full_command+=("nmap" "${_cmd[@]}")
 
-  local _args=("$@")
+  # shellcheck disable=SC2154
+  if [[ ! -z "$report" ]] ; then
 
-  local _cmd_begtime="0"
-  local _cmd_endtime="0"
-  local _cmd_totaltime="0"
+    case $report in
 
-  _logger "info" \
-    "${_FUNCTION_ID}()" \
-    "init function: '${_args[*]}'"
+      standard)
 
-  # In these two variables we store the message to display
-  # and the command to execute.
-  export _msg_args=()
-  export _cmd_args=()
+        _output_opt="-oN"
+        # shellcheck disable=SC2154
+        _output_path="${_output_directory}/scan.$(date +%s).nmap"
+        _output_targ=" ${_output_opt} ${_output_path}" ;;
 
-  eval "${_args[@]}" ; if [ ! $? ] ; then _exit_ 255 ; fi
+      xml)
 
-  _num="${#_msg_args[@]}"
-  for (( _xa="0" ; _xa<=((_num - 1)) ; _xa++ )) ; do
+        _output_opt="-oX"
+        _output_path="${_output_directory}/scan.$(date +%s).xml"
+        _output_targ=" ${_output_opt} ${_output_path}" ;;
 
-    _msg="${_msg_args[$_xa]}"
-    _full_command="${_cmd_args[$_xa]}"
+      grep)
 
-    _sprintf "info" "$_msg"
+        _output_opt="-oG"
+        _output_path="${_output_directory}/scan.$(date +%s).grep"
+        _output_targ=" ${_output_opt} ${_output_path}" ;;
 
-    _logger "info" \
-      "${_FUNCTION_ID}()" \
-      "$_msg"
+      *) true ;;
 
-    _cmd_begtime=$(date +%s)
+    esac
 
-    _init_cmd "$_full_command" ; if [ ! "$?" ] ; then _exit_ 255 ; fi
+  fi
 
-    _cmd_endtime=$(date +%s)
+  if [[ ! -z "$_output_path" ]] ; then
 
-    # shellcheck disable=SC2154
-    if [[ "$time_mode" -eq 1 ]] && [[ "$_cmdtime_state" -eq 1 ]] ; then
+    _full_command+=("$_output_targ")
 
-      _cmd_totaltime=$((_cmd_endtime - _cmd_begtime))
+  fi
 
-      _cmd_totaltime_out=$(printf '%dh:%dm:%ds' \
-      $((_cmd_totaltime/3600)) $((_cmd_totaltime%3600/60)) $((_cmd_totaltime%60)))
+  if [[ "$terminal" == "external" ]] ; then
 
-      _sprintf "info" "time: $_cmd_totaltime_out"
+    printf "\n\e[1;39m%s\e[m:\n" "command"
+    printf "\e[1;39m%c\e[m \e[0;30m%s\e[m\n\n" ">" "${_full_command[*]}"
 
-      _logger "info" \
-        "${_FUNCTION_ID}()" \
-        "time: $_cmd_totaltime_out"
+  else
+
+    printf "\n\e[1;39m%s\e[m:\n" "command"
+    printf "\e[1;39m%c\e[m \e[0;30m%s\e[m\n" ">" "${_full_command[*]}"
+
+  fi
+
+  # Execute command and exit.
+  # For shellcheck code:
+  #   - after closing the array with double quotes, some commands are not executed properly
+  if [[ "$terminal" == "external" ]] ; then
+
+    # shellcheck disable=SC2068
+    ${_full_command[@]} &
+
+  else
+
+    # shellcheck disable=SC2068
+    ${_full_command[@]} ; _state="$?"
+
+    if [[ "$_state" -eq 0 ]] ; then
+
+      printf "\n\e[1;39m%s\e[m: \e[0;32m%s\e[m\n\n" "Result" "pass"
+
+    else
+
+      printf "\n\e[1;39m%s\e[m: \e[0;31m%s\e[m\n\n" "Result" "fail"
 
     fi
 
-  done
+  fi
 
-  _cmdtime_state="0"
+  _STATE=$_state
 
-  return "$_STATE"
+  return $_STATE
 
 }
 
